# Generated by Django 4.2 on 2023-04-29 16:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='userm',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=30, null=True)),
                ('comp', models.BooleanField(default=False, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Requests',
            fields=[
                ('request_id', models.AutoField(primary_key=True, serialize=False)),
                ('is_accepted', models.BooleanField(default=False)),
                ('payment_completed', models.BooleanField(default=False)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='company',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cemail', models.CharField(max_length=30, null=True)),
                ('cname', models.CharField(max_length=30, null=True)),
                ('ccontact', models.CharField(max_length=30, null=True)),
                ('cgstin', models.CharField(max_length=30, null=True)),
                ('ccity', models.CharField(max_length=30, null=True)),
                ('cstate', models.CharField(max_length=30, null=True)),
                ('czip', models.CharField(max_length=30, null=True)),
                ('ccost', models.CharField(max_length=30, null=True)),
                ('cdis', models.CharField(max_length=300, null=True)),
                ('cimage', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('comp', models.BooleanField(default=True, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BookingRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.company')),
                ('request_list', models.ManyToManyField(blank=True, related_name='request', to='website.requests')),
            ],
        ),
    ]
