# Generated by Django 4.2 on 2023-04-29 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_alter_requests_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='requests',
            name='company_name',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
