# Generated by Django 4.2 on 2023-04-30 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_requests_cost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='ccost',
        ),
        migrations.AddField(
            model_name='company',
            name='cost',
            field=models.IntegerField(null=True),
        ),
    ]
