# Generated by Django 4.2 on 2023-04-28 19:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('website', '0005_remove_company_ccity_remove_company_ccontact_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='ccity',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='ccontact',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='ccost',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='cdis',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='cemail',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='cgstin',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='cimage',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='company',
            name='cname',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='comp',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='cstate',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='czip',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userm',
            name='comp',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
