# Generated by Django 4.2 on 2023-04-30 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_remove_company_ccost_company_cost'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='cost',
            new_name='ccost',
        ),
    ]
